/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ru.model.SmartCalc.xml -i applicationcontroller.h -a controllerAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd and other contributors.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "controllerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SmartCalcAdaptor
 */

SmartCalcAdaptor::SmartCalcAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SmartCalcAdaptor::~SmartCalcAdaptor()
{
    // destructor
}

double SmartCalcAdaptor::calculateExpression(const QString &expression)
{
    // handle method call ru.model.SmartCalc.calculateExpression
    double out0;
    QMetaObject::invokeMethod(parent(), "calculateExpression", Q_RETURN_ARG(double, out0), Q_ARG(QString, expression));
    return out0;
}

