/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ru.model.CreditCalc.xml -i creditcalccontroller.h -a creditCalcAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd and other contributors.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "creditCalcAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CreditCalcAdaptor
 */

CreditCalcAdaptor::CreditCalcAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CreditCalcAdaptor::~CreditCalcAdaptor()
{
    // destructor
}

QStringList CreditCalcAdaptor::calculate(const QString &totalLoanAmount, const QString &term, const QString &interestRate, const QString &isAnnuity)
{
    // handle method call ru.credit.CreditCalc.calculate
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "calculate", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, totalLoanAmount), Q_ARG(QString, term), Q_ARG(QString, interestRate), Q_ARG(QString, isAnnuity));
    return out0;
}

