start:
	./model/smartCalcModel/build/model &
	./model/creditCalcModel/build/creditCalcModel &
	./viewCalc/build/viewCalc

install:
	make -C model/smartCalcModel install
	make -C model/creditCalcModel install
	make -C viewCalc install

uninstall:
	make -C model/smartCalcModel uninstall
	make -C model/creditCalcModel uninstall
	make -C viewCalc uninstall
